/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from 'ethers'
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from '@ethersproject/contracts'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'

interface ICustomTokenInterface extends ethers.utils.Interface {
  functions: {
    'registerL2Token(address)': FunctionFragment
  }

  encodeFunctionData(
    functionFragment: 'registerL2Token',
    values: [string]
  ): string

  decodeFunctionResult(
    functionFragment: 'registerL2Token',
    data: BytesLike
  ): Result

  events: {}
}

export class ICustomToken extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  on(event: EventFilter | string, listener: Listener): this
  once(event: EventFilter | string, listener: Listener): this
  addListener(eventName: EventFilter | string, listener: Listener): this
  removeAllListeners(eventName: EventFilter | string): this
  removeListener(eventName: any, listener: Listener): this

  interface: ICustomTokenInterface

  functions: {
    registerL2Token(
      l2Address: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>

    'registerL2Token(address)'(
      l2Address: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>
  }

  registerL2Token(
    l2Address: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  'registerL2Token(address)'(
    l2Address: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>

  callStatic: {
    registerL2Token(l2Address: string, overrides?: CallOverrides): Promise<void>

    'registerL2Token(address)'(
      l2Address: string,
      overrides?: CallOverrides
    ): Promise<void>
  }

  filters: {}

  estimateGas: {
    registerL2Token(
      l2Address: string,
      overrides?: Overrides
    ): Promise<BigNumber>

    'registerL2Token(address)'(
      l2Address: string,
      overrides?: Overrides
    ): Promise<BigNumber>
  }

  populateTransaction: {
    registerL2Token(
      l2Address: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>

    'registerL2Token(address)'(
      l2Address: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>
  }
}
